name: "RVC to MQTT Bridge"
description: "Bridging RVC CAN bus data to MQTT for Home Assistant."
version: "1.0.93"
slug: "rvc2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
ports:
  80/tcp: 80
options:
  mqtt_user: "your_mqtt_user"
  mqtt_password: "your_mqtt_password"
schema:
  mqtt_user: "str"
  mqtt_password: "str"
volumes:
  - 'share:/share'
host_network: true
devices:
  - /dev/can0
  - /dev/net/can
full_access: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_RAWIO
host_dbus: true
#apparmor: false
# Add capabilities for network and device access
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:80/health"]
  interval: 30s
  timeout: 10s
  retries: 3
