# Home Assistant configuration for Water Heater entities
# Add these entries to your configuration.yaml

mqtt:
  sensor:
    # Operating Mode
    - name: "RVC Water Heater Mode"
      unique_id: rvc_waterheater_mode
      state_topic: "RVC/WATERHEATER_STATUS/+/operating_modes"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:water-boiler"
      options:
        - "off"
        - "combustion"
        - "electric"
        - "gas electric"
        - "automatic"
        - "test combustion" 
        - "test electric"
      
    # Set Point Temperature
    - name: "RVC Water Heater Set Point"
      unique_id: rvc_waterheater_setpoint
      state_topic: "RVC/WATERHEATER_STATUS/+/set_point_temperature"
      value_template: "{{ value }}"
      device_class: "temperature"
      state_class: "measurement"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      
    # Water Temperature
    - name: "RVC Water Heater Temperature"
      unique_id: rvc_waterheater_temp
      state_topic: "RVC/WATERHEATER_STATUS/+/water_temperature"
      value_template: "{{ value }}"
      device_class: "temperature"
      state_class: "measurement"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-water"
      
    # Thermostat Status
    - name: "RVC Water Heater Thermostat Status"
      unique_id: rvc_waterheater_thermostat_status
      state_topic: "RVC/WATERHEATER_STATUS/+/thermostat_status"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:thermostat"
      options:
        - "set point met"
        - "set point not met"
        
    # Burner Status
    - name: "RVC Water Heater Burner Status"
      unique_id: rvc_waterheater_burner_status
      state_topic: "RVC/WATERHEATER_STATUS/+/burner_status"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:fire"
      options:
        - "off"
        - "ac element is active"
        
    # AC Element Status
    - name: "RVC Water Heater AC Element Status"
      unique_id: rvc_waterheater_ac_element_status
      state_topic: "RVC/WATERHEATER_STATUS/+/ac_element_status"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:power-plug"
      options:
        - "no fault"
        - "open neutral fault detected"
        
    # High Temperature Limit Switch Status
    - name: "RVC Water Heater High Temp Limit"
      unique_id: rvc_waterheater_high_temp_limit
      state_topic: "RVC/WATERHEATER_STATUS/+/high_temperature_limit_switch_status"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:thermometer-alert"
      options:
        - "limit switch not tripped"
        - "limit switch tripped"
        
    # Failure to Ignite Status
    - name: "RVC Water Heater Ignition Status"
      unique_id: rvc_waterheater_ignition_status
      state_topic: "RVC/WATERHEATER_STATUS/+/failure_to_ignite_status"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:fire-alert"
      options:
        - "no failure"
        - "failed to ignite"
        
    # AC Power Failure Status
    - name: "RVC Water Heater AC Power Status"
      unique_id: rvc_waterheater_ac_power_status
      state_topic: "RVC/WATERHEATER_STATUS/+/ac_power_failure_status"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:power-plug"
      options:
        - "ac power present"
        - "ac power not present"
        
    # DC Power Failure Status
    - name: "RVC Water Heater DC Power Status"
      unique_id: rvc_waterheater_dc_power_status
      state_topic: "RVC/WATERHEATER_STATUS/+/dc_power_failure_status"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:power-plug-battery"
      options:
        - "dc power present"
        - "dc power not present"
        
    # Electric Element Level
    - name: "RVC Water Heater Element Level"
      unique_id: rvc_waterheater_element_level
      state_topic: "RVC/WATERHEATER_STATUS_2/+/Electric_Element_Level"
      value_template: "{{ value }}"
      icon: "mdi:gauge"
      
    # Electric Element Max Level
    - name: "RVC Water Heater Max Element Level"
      unique_id: rvc_waterheater_max_element_level
      state_topic: "RVC/WATERHEATER_STATUS_2/+/Max_Electric_Element_Level"
      value_template: "{{ value }}"
      icon: "mdi:gauge-max"
      
    # Engine Preheat Status
    - name: "RVC Water Heater Engine Preheat"
      unique_id: rvc_waterheater_engine_preheat
      state_topic: "RVC/WATERHEATER_STATUS_2/+/Engine_Preheat"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:engine"
      options:
        - "Off"
        - "On"
        - "Test (Forced On)"
        
    # Coolant Level Warning
    - name: "RVC Water Heater Coolant Level"
      unique_id: rvc_waterheater_coolant_level
      state_topic: "RVC/WATERHEATER_STATUS_2/+/Coolant_Level_Warning"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:coolant-temperature"
      options:
        - "Coolant level sufficient"
        - "Coolant level low"
        
    # Hot Water Priority
    - name: "RVC Water Heater Priority"
      unique_id: rvc_waterheater_priority
      state_topic: "RVC/WATERHEATER_STATUS_2/+/Hot_Water_Priority"
      value_template: "{{ value }}"
      device_class: "enum"
      icon: "mdi:water-boiler"
      options:
        - "Domestic water priority"
        - "Heating priority"

  # Simple switches for basic control
  switch:
    # Switch to toggle between off and automatic mode
    - name: "RVC Water Heater Power"
      unique_id: rvc_waterheater_power
      command_topic: "RVC/WATERHEATER_COMMAND/set"
      state_topic: "RVC/WATERHEATER_STATUS/+/operating_modes"
      value_template: "{{ 'ON' if value != 'off' else 'OFF' }}"
      payload_on: '{"instance": 1, "operating_modes": 4}'
      payload_off: '{"instance": 1, "operating_modes": 0}'
      state_on: "ON"
      state_off: "OFF"
      icon: "mdi:water-boiler"
      
    # Switch for electric mode
    - name: "RVC Water Heater Electric Mode"
      unique_id: rvc_waterheater_electric
      command_topic: "RVC/WATERHEATER_COMMAND/set"
      state_topic: "RVC/WATERHEATER_STATUS/+/operating_modes"
      value_template: "{{ 'ON' if value == 'electric' else 'OFF' }}"
      payload_on: '{"instance": 1, "operating_modes": 2}'
      payload_off: '{"instance": 1, "operating_modes": 0}'
      state_on: "ON"
      state_off: "OFF"
      icon: "mdi:electric-switch"
      
    # Switch for combustion mode
    - name: "RVC Water Heater Combustion Mode"
      unique_id: rvc_waterheater_combustion
      command_topic: "RVC/WATERHEATER_COMMAND/set"
      state_topic: "RVC/WATERHEATER_STATUS/+/operating_modes"
      value_template: "{{ 'ON' if value == 'combustion' else 'OFF' }}"
      payload_on: '{"instance": 1, "operating_modes": 1}'
      payload_off: '{"instance": 1, "operating_modes": 0}'
      state_on: "ON"
      state_off: "OFF"
      icon: "mdi:fire"

  # Number entity for temperature control
  number:
    - name: "RVC Water Heater Temperature"
      unique_id: rvc_waterheater_temp_control
      command_topic: "RVC/WATERHEATER_COMMAND/set"
      command_template: '{"instance": 1, "set_point_temperature": {{ value }} }'
      state_topic: "RVC/WATERHEATER_STATUS/+/set_point_temperature"
      value_template: "{{ value }}"
      min: 40
      max: 65
      step: 1
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      
  # Select for mode control
  select:
    - name: "RVC Water Heater Mode"
      unique_id: rvc_waterheater_mode_select
      command_topic: "RVC/WATERHEATER_COMMAND/set"
      command_template: >-
        {"instance": 1, "operating_modes": 
          {% if value == "off" %} 0
          {% elif value == "combustion" %} 1
          {% elif value == "electric" %} 2
          {% elif value == "gas electric" %} 3
          {% elif value == "automatic" %} 4
          {% endif %}
        }
      state_topic: "RVC/WATERHEATER_STATUS/+/operating_modes"
      value_template: "{{ value }}"
      options:
        - "off"
        - "combustion"
        - "electric"
        - "gas electric"
        - "automatic"
      icon: "mdi:water-boiler"

# Advanced controls using scripts
script:
  water_heater_electric_low_enable:
    alias: "Water Heater - Enable Electric Low"
    sequence:
      - service: mqtt.publish
        data:
          topic: "RVC/WATERHEATER_COMMAND_2/set"
          payload: '{"Instance": 1, "Command": 0}'
          
  water_heater_electric_low_disable:
    alias: "Water Heater - Disable Electric Low"
    sequence:
      - service: mqtt.publish
        data:
          topic: "RVC/WATERHEATER_COMMAND_2/set"
          payload: '{"Instance": 1, "Command": 1}'
          
  water_heater_burner_enable:
    alias: "Water Heater - Enable Burner"
    sequence:
      - service: mqtt.publish
        data:
          topic: "RVC/WATERHEATER_COMMAND_2/set"
          payload: '{"Instance": 1, "Command": 6}'
          
  water_heater_burner_disable:
    alias: "Water Heater - Disable Burner"
    sequence:
      - service: mqtt.publish
        data:
          topic: "RVC/WATERHEATER_COMMAND_2/set"
          payload: '{"Instance": 1, "Command": 7}'